Aikindapps/Nuance

src/PostBucket/main.mo, src/PostBucket/types.mo, src/shared/utils.mo
Implemented all the needed functions & hashmaps to commenting in the PostBucket canister. Added the explanation of each function as comment in the code.
=> The backend of the comment article feature.

src/PostCore/main.mo, src/PostCore/modclub/modclub.mo
Added new modclub interface, we will still need to re-register with modclub canister once deployed
=> added new modclub interface and canister ids

src/PostBucket/main.mo, src/PostBucket/types.mo, src/PostCore/main.mo, src/shared/CanisterDeclarations.mo, src/shared/env.mo, src/shared/sonic.mo, src/shared/utils.mo
This PR is based to the branch comment-frontend-1386 to protect the code freeze in the master branch. It contains all the backend functionality of the tipping feature.
=> Tipping feature backend

Nuance-NFTs-and-Publications/src/shared/versions.mo, src/shared/versions.mo
adjusted the canister version names
=> adjusted the canister version names

Nuance-NFTs-and-Publications/src/shared/env.mo, src/PostCore/main.mo, src/shared/env.mo
Debugged the logic for calculating number of applauds in PostCore canister.
=> Fix for the bug ticket 1434

src/nuance_assets/UI/dropdown/dropdown.tsx, src/nuance_assets/UI/profile-picture-button/profile-picture-button.tsx, src/nuance_assets/components/card-draft-articles/card-draft-articles.tsx, src/nuance_assets/components/card-editor-publication/card-editor-publication.tsx, src/nuance_assets/screens/create-edit-publication/create-edit-publication.tsx, src/nuance_assets/screens/home/homegrid.tsx, src/nuance_assets/screens/profile/publicationLink.tsx, src/nuance_assets/screens/profile/wallet.tsx, src/nuance_assets/screens/timed-out/timedOut.tsx, src/nuance_assets/store/authStore.ts, src/nuance_assets/store/userStore.ts
Resolved the following bugs:
- 1431 (Logout not working first time for NFID)
- 1456 (Cannot delete first writer)
- 1443 (Publication list disabled bold)
- 1408 (Search for publication not working)
- 1433 (Wierd UI after timeout)
- 1462 (Image on register cropping wierd)
- 1442 (Drop down - you should be ashamed of yourselves)
- 1448 (Applause vs Applaud)
=> Fixed the bug tickets

package-lock.json, src/nuance_assets/index.tsx, src/nuance_assets/store/authStore.ts
Added flush method per the advice of the usergeek team, updated npm package, and also added a log for the init method for debugging purposes. Also a reminder to run `npm i`
=> usergeek flush method and logging

src/shared/versions.mo
=> Just version names

src/nuance_assets/App.tsx, src/nuance_assets/services/icp-index/index.js, src/nuance_assets/services/icrc1/index.js, src/nuance_assets/store/authStore.ts
To test:
1. open 2 tabs
2. Log into 1 tab
* Notice the second tab is now logged in
3. Log out of 1 tab
* notice second tab is logged out
=> added channels to sync tab session storage

proxy/src/actor.ts, proxy/src/screens/home.ts, proxy/src/screens/post.ts, proxy/src/screens/userProfile.ts, proxy/src/server.ts
Can be tested locally:
1. in `server.ts` at end of the file, change server.listen to your port of choice. (or use 8080 as default)
2. cd into the proxy dir
3. run `tsc`
4. run `node dist/server.js`
Now you can navigate to localhost:8080. You should experience a proxy of production through localhost. For this PR we need to test the behavior of crawlers:
1. Open console
2. Navigate through the top right kebab menu --> more tools --> network conditions
3. Under network condition settings, remove check from "use browser default" and select `googlebot` as your user agent.
4. Now you can navigate visually and see what a crawler will see. 
Note: 
- You should still observe normal behavior when using the default user agent for all screens. 
- Sometimes when switching on the user agent to …
=> Keywords and SEO improvements

scripts/buildPublications.sh, scripts/migrations/tagsFix.sh, src/PostCore/main.mo, src/PostCore/types.mo, src/nuance_assets/screens/publication-landing/publication-landing.tsx
To test tags migration:
1. `in scripts/migrations/tagsFix.sh` update variables for your environment. Currently the script is setup for PROD as far as bucket CID, timestamp (you can add any timestamp in the future to test), and post range. 
```
//example
bucketCanister="bkyz2-fmaaa-aaaaa-qaaaq-cai"
timeStamp=16901674982590 
postId=1
endPostId=10
```
2. run  bash scripts/migrations/tagsFix.sh
- To test publication landing bug, try different screen sizes, paying attention to the left sidebar. 
- Still requires fixes for NFT creation
=> Small updates to dev install, publication landing bug, and tag migration

src/nuance_assets/screens/create-edit-publication/create-edit-publication.tsx
the website field was using the website value of the user instead of the publicationWebsite value. Fixed that.
=> Bug ticket 1616 - Publication website

src/nuance_assets/screens/profile/profileSidebar.tsx
navigated user to homepage if not logged in and the my-profile screen is open
=> Bug ticket 1619

src/nuance_assets/components/clap-modal/clap-modal.tsx
This was created from `rustyNail v3` to fix a bug in tipping.
=> tipping amount is always NUA

Nuance-NFTs-and-Publications/src/shared/env.mo, src/nuance_assets/UI/author-profile-sidebar/_author-profile-sidebar.scss, src/nuance_assets/UI/author-profile-sidebar/author-profile-sidebar.tsx, src/shared/env.mo
=> fixed bug-1725

src/nuance_assets/components/clap-modal/clap-modal.tsx
=> fixed bug-1722

src/PostCore/main.mo, src/nuance_assets/screens/user/profile.tsx
=> fixed bug-1694

src/nuance_assets/UI/InputField2/InputField2.tsx, src/nuance_assets/screens/create-edit-publication/create-edit-publication.tsx, src/nuance_assets/screens/profile/edit-profile/editProfile.tsx
Added a logic that trim the trailing blank space in the social channel links that prevent profile changes from being saved.
=> fixed bug 1760

package-lock.json, package.json, src/nuance_assets/components/header-image/header-image.tsx, src/nuance_assets/index.html, src/nuance_assets/screens/read-article/_read-article.scss, src/nuance_assets/screens/read-article/read-article.tsx
Created a HeaderImage component and preloaded it via @loadable/components. Also, added link tags to HTML document to preconnect Google fonts.
=> Reduce LCP read article screen

src/PostBucket/main.mo
Added a condition to check if the caller is the author of the article.
=> writers can always see their own article

src/nuance_assets/store/postStore.ts
Added comment repliers' principals to creators array to fetch all principal IDs in comments.
=> fixed bug 1783

package-lock.json, package.json, src/nuance_assets/components/quill-text-editor/_quill-text-editor.scss, src/nuance_assets/components/quill-text-editor/model_config.ts, src/nuance_assets/components/quill-text-editor/modules/commonWords.ts, src/nuance_assets/components/quill-text-editor/modules/phraseCompletion.ts, src/nuance_assets/components/quill-text-editor/modules/quill-modules.d.ts, src/nuance_assets/components/quill-text-editor/modules/quill-webllm-autocomplete.ts, src/nuance_assets/components/quill-text-editor/modules/quill-webllm-autocomplete.worker.ts, src/nuance_assets/components/quill-text-editor/modules/utils.ts, src/nuance_assets/components/quill-text-editor/modules/wordCompletion.ts, src/nuance_assets/components/quill-text-editor/quill-text-editor.tsx
Give it a minute or two to load in your browser ;)
=> autocomplete
